name: CI

on:
  push:
    branches:
      - feature/v1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Dev stage
      run: | 
        chmod 740 ./scripts/ci-dev.sh
        ./scripts/ci-dev.sh