name: CI

on:
  push:
    branches:
      - feature/v1

jobs:
  build:
    runs-on: ubuntu-latest
    container: 7perl/build-packs:android-29-ndk-21
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Dev stage
      env:
        TEST: ${{ secrets.TEST }}
      run: | 
        ls -l -a
        pwd
        echo $PWD
        echo "$TEST"
        echo "====="
        chmod 740 ./.ci/scripts/ci-dev.sh
        ./.ci/scripts/ci-dev.sh $PWD