name: CI

on:
  push:
    branches:
      - feature/v1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@feature/v1
    - name: Dev stage
      run: | 
        ls -l