name: CI

on:
  push:
    branches:
      - feature/v1

jobs:
  build:
    runs-on: ubuntu-latest
    container: 7perl/build-packs:android-29-ndk-21
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Dev stage
      env:
        TEST: ${{ secrets.TEST }}
        B2_APP_ID: ${{ secrets.B2_APP_ID }}
        B2_APP_KEY: ${{ secrets.B2_APP_KEY }}
      run: | 
        ./.ci/scripts/ci-dev.sh $PWD